[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "genai-ecommerce"
version = "0.1.0"
description = "GenAI E-commerce project with ML-powered recommendations"
requires-python = ">=3.12,<3.13"

dependencies = [
    "genai_ecommerce_core",
    "genai_ecommerce_web",
    "genai_ecommerce_ml",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "UP", "N", "ANN", "S", "A"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_optional = true

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.2.0",
    "mypy>=1.8.0",
    "ipykernel>=6.0.0",
]