[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "genai_ecommerce_web"
version = "0.1.0"
description = "Web interface for GenAI E-commerce project"
requires-python = ">=3.12,<3.13"

dependencies = [
    "genai_ecommerce_core",
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.9",
    "aiofiles>=23.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/genai_ecommerce_web"]

[tool.hatch.metadata]
allow-direct-references = true