[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "genai_ecommerce_core"
version = "0.1.0"
description = "Core functionality for GenAI E-commerce project"
requires-python = ">=3.12,<3.13"

dependencies = [
    "pydantic>=2.6.0",
    "httpx>=0.26.0",
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.19.0",
    "pillow>=10.0.0",
    "pyyaml>=6.0.1",
    "python-dateutil>=2.8.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/genai_ecommerce_core"]